export const CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";

export const CREATE_RECIPE_START = "CREATE_RECIPE_START";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_FAILED = "CREATE_RECIPE_FAILED";

export const CREATE_FOOD_START = "CREATE_FOOD_START";
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS";
export const CREATE_FOOD_FAILED = "CREATE_FOOD_FAILED";

export const CREATE_SERVICE_START = "CREATE_SERVICE_START";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAILED = "CREATE_SERVICE_FAILED";

export const CREATE_MASTERCLASS_START = "CREATE_MASTERCLASS_START";
export const CREATE_MASTERCLASS_SUCCESS = "CREATE_MASTERCLASS_SUCCESS";
export const CREATE_MASTERCLASS_FAILED = "CREATE_MASTERCLASS_FAILED";
