const paymentDatas=[
    {
        heading:'Introduction & Scope.',
        description:'Welcome, this is the Billing Policy (hereinafter, the “Terms”) for our platform available at the URL www.pinchef.io, including its sub-domains and its mobile optimized versions, the mobile application known as PinChef (collectively called “PinChef”), along with any products and services offered thereby.  These specific Terms apply to all our registered end users (both Chefs and Guests), and any other sections and defined terms referenced in our Main Terms and Conditions of Service (available here) and our Terms for Accounts for Guests and Chefs (available here) shall have the meaning indicated there, thereby considered material part of this document.'
    },
    {
        heading:'Payment Terms for Chefs.',
        description:'Our platform will facilitate to set up payments made by Guests, and PinChef may also assist Chefs in issues relating to payment disputes, fraud and/or chargebacks.  Chefs hereby agree that all payments made by your Guests through PinChef will be collected and processed via our available payment processors. Net payments made by Guests will be deposited directly into Chef’s payment account, less the deduction of the following fees: (i) payment processing fees which are applied by payment processors or other financial institutions. We do not manage, account for or make any tax withholdings in connection with applicable federal, provincial, state, local or other governmental sales, goods and services or other taxes, fees, or charges, whether now in force or enacted in the future.  Each Chef is responsible for the compliance and fulfillment of its tax obligations, no exceptions.'
    },
    {
        heading:'Refunds for Guests.',
        description:'One-time purchases (such as online courses and e-Masterclasses) have a cool-off period where they can be canceled by Chefs (XX hours) or Guests (XX hours).  After the cancellation period ends, there will be no refunds for one-time purchases, even if the Guest refuses or is unable to receive the product. Chefs may cancel the e-Masterclass only in some special cases, such as for personal matters.  Cancellation will require a written reason from Chef directed to us, which will also be sent to all Guests that already bought tickets to that class.  If the reason is a force majeure reason and not by the fault of the Chef, the refund will be done to Guests, deducting the transaction fee of PinChef, but if the cancellation reason results to be the Chefs fault, then the Chef will accept the responsibility of the payment of the transaction fees and the Guest will be fully refunded. If one of the Chef’s live classes gets cancelled and the Chef does inform us at least twenty-four hours in advance, Guests will be sent an apology and users will receive a full refund as per the timing and terms of the selected payment processor.  In such case, the Chef account will be debited for our fees and expenses, and such credit will be applied to the next earnings distribution for the Chef.'
    },
    {
        heading:'Payment Processing Terms.',
        description:'We rely on authorized third-party payment processors in order to bill all users you through a linked payment account, such as debt, credit cards and third party platforms, and henceforth you hereby authorize us to charge the pertinent fees through your indicated payment processing account.  Sensitive financial details are stored only by our payment providers. Such third party payment processors are also the ones that process, manage, operate and deliver the payments of your end customers, not PinChef.  For more information, please refer to the terms of use of our third party payment processing platform, which may include Stripe, PayPal and those used by Apple, Google and others. Please also review our policy for in app purchases below.  PinChef may change Membership fees at any time or start charging Membership fees to things that were previously free. As applicable, PinChef will give you advance notice of Membership fee changes for Chefs.  If a Chef does not agree with the changes, he/she may cancel the Membership subscription, or if agreeing, will be charged in accordance with the new Membership fees. PinChef shall not be held responsible for any and all errors, fees and currency conversion fees by our payment processors, and you should review its terms and policies from time to time, which will govern the provision of Services to our users. Agent Appointment.  You hereby appoint PinChef as your payment agent when you provide a payment credential to us, and therefore you acknowledge and agree that we will be permitted to use, collect and process that payment credential in order to process payments, charges and fees of PinChef.  We may also use certain payment card updater services, whose availability varies by issuer, to ensure we have the most up-to-date information about the payment credentials that we store. For payments by credit or debit card, we will have the right to obtain a pre-approval from the issuer of the card for an amount which may be a low verification amount or as high as the full price of the payment.  In such case, your card will be charged when you initiate a payment on PinChef, and if you cancel a transaction before it can be completed, the security pre-approval may cause those charges to be available to you on your account’s limit.'
    },
    {
        heading:'Payments made person to person.',
        description:'PinChef may activate person to person payments for selected products and services offered by our Chefs.  Such payments may include cash option and also debit and credit card option.  Such payments can only be used for the payment of products and services offered by Chefs to Guests via PinChef, and any use for other personal, business, commercial or merchant transactions is explicitly forbidden to all users. Chefs who receive and accept a person to person payment will be liable to us for the full payment amount and also for any third-party fees which may arise from subsequent charge reversal and invalidation, including but not limiting, debit or credit card claims and chargebacks.  For more information, please refer to our chargebacks section. Chefs will be able to use their payment processing account linked to their PinChef account for remittance of amounts and consolidation of charges and fees with PinChef.  All of these charge credits are net 30. If we detect any evidence of undercharges, overcharges or payments not related to PinChef, we reserve the right to freeze, deactivate or delete any user account.  For recurring cases, we may deactivate person to person payments to such users, and we may also reverse or place a hold on your present and future transactions. Person to person payments will be done in accordance with all local, state and federal laws applying to each case, and cannot be used in relation to any illegal or illicit activity. Lastly, these types of payments are undertaken at the sole and final risk of all users, and PinChef hereby disclaims any and all liability for each transaction person to person.  We will not cover disputes among users regarding products and services and payment done person to person, nor listen or study the arguments of either party, nor will we be held responsible for making any pronunciation on the matter.'
    },
    {
        heading:'Disputes & Charge-backs.',
        description:'All users must provide us with valid and current billing information.  Except as expressly set forth herein, all payment charges are final and non-cancelable.  If your transaction results in an overdraft or other fee from your bank, or if we detect any chargeback or if any payment is not received by us or our payment processors for any reason, you will promptly pay us any and all amounts due to us upon notice.  Any failure or inability by us to process any payment hereunder does not relieve you from your payment obligations. A chargeback is typically caused when a customer disputes a charge that appears on their bank or payment processing statement.  A charge-back may result in the reversal of a transaction, with the amount charged back to you.  You can be assessed chargebacks for: (i) customer disputes; (ii) unauthorized or improperly authorized transactions; (iii) transactions that do not comply with payment processor network rules or are allegedly unlawful or suspicious; or (iv) any reversals for any reason by our payment processor or the institutions handling the transaction. When a chargeback is issued, you are immediately liable to PinChef for the full amount of payment of the chargeback, plus any associated fees, fines, expenses or penalties (including those assessed by our payment processor or the financial institutions handling the transaction).  Accordingly, you hereby represent and warrant that you expressly appoint PinChef as your agent, with full power to recover these amounts by debiting your account or setting off any amounts owed to you by us. If we are unable to recover funds related to a charge-back for which you are liable, you will pay us the full amount of the chargeback immediately upon demand; thus you agree to pay all costs and expenses, including without limitation, costs assessed by our payment processor, legal fees and other legal expenses, incurred by or on behalf of us in connection with the collection of any unpaid charge-backs unpaid by you.'
    },
    {
        heading:'In-App Purchase Terms.',
        description:'If in the future we may allow any user to make a one-time purchase through PinChef, where Guests will be prompted to enter details for their account with their selected app store account, which will be charged for the in-app purchase in accordance with the terms disclosed to you at the time of purchase as well as the general terms for in app purchases that apply to your App Store account. For Chefs who purchase an auto-recurring periodic Membership subscription through an in-app purchase, their App Store account will be billed continuously for the subscription until cancelled.  After your initial subscription commitment period, and again after any subsequent subscription period, your Membership will automatically continue for an additional equivalent period, at the price you agreed to when subscribing.  If you do not wish your Membership to renew automatically, or if you want to change or terminate your subscription, you will need to log in to your App Store account and follow instructions to cancel your subscription, even if you have otherwise deleted your account with PinChef or if you have deleted our mobile application from your device.  The App Stores may charge you sales tax, depending on where you live. Please take note that deleting your Chef account on PinChef or deleting it from your device may not cancel your ongoing Membership subscription; and in such case, we will continue charging all funds via your App Store account until you cancel your subscription.'
    },
    {
        heading:'Contact',
        description:'If you have any questions or queries about us, the PinChef, our Services or these Terms, please contact us via support@chef.io.  Note that communications made to support@chef.io or the “Contact Us” page does not constitute legal notice to the PinChef legal entity. BKNY Technology LLC 17030 Collins Ave, Suite 117 Sunny Isles Beach, Miami, Florida 33160'
    }
]

export default paymentDatas